FROM arm32v7/node:dubnium-buster

RUN apt-get update && apt-get install -y --no-install-recommends build-essential libsecret-1-dev fakeroot rpm libx11-dev libxkbfile-dev git libgtk-3-dev libxss-dev libasound2-dev && rm -rf /var/lib/apt/list/*

